### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by softwarestesting** [callmearta/clubhouse-desktop#12]
Unhandled Error has occurred when click Help-->Clubhouse Desktop Client after start desktop application.

Error: Image could not be created from C:/Users/IEUser/Downloads/clubhouse-win32-x64/resources/app.asar/static/icon.png
    at messageBox (electron/js2c/browser_init.js:45:3898)
    at Object.showMessageBox (electron/js2c/browser_init.js:45:4196)
    at Object.exports.showAboutWindow (C:/Users/IEUser/Downloads/clubhouse-win32-x64/resources/app.asar/node_modules/electron-util/index.js:228:13)
    at click (C:/Users/IEUser/Downloads/clubhouse-win32-x64/resources/app.asar/node_modules/electron-util/index.js:256:12)
    at MenuItem.click (electron/js2c/browser_init.js:69:1626)
    at Object.l._executeCommand (electron/js2c/browser_init.js:77:2328)

**Comment by callmearta** [comment]
I really didn't think anyone would click on the help menu :)) It's not a serious bug but it will be fixed in the next release.
